[package]
authors = ["Eric Trombly <etrombly@gmail.com>"]
description = "Rust library for OsmGpsMap-1.0"
license = "MIT"
keywords = ["openstreetmap", "gtk", "map", "widget"]
name = "osmgpsmap"
readme = "README.md"
repository = "https://github.com/etrombly/osmgpsmap-rs"
version = "0.2.1"

[dependencies]
osmgpsmap-sys = "^0.2"
gdk = "^0.8"
gdk-pixbuf = "^0.4"
glib = "^0.5"
glib-sys = "^0.6"
gobject-sys = "^0.6"
gtk = "^0.4"
gtk-sys = "^0.6"
libc = "^0.2"

[dependencies.cairo-rs]
version = "^0.4"
#path = "../cairo"
features = ["use_glib"]

[dev-dependencies]
gio = "^0.4"