[options]
girs_dir = "gir-files"
library = "OsmGpsMap"
version = "1.0"
min_cfg_version = "1.0"
work_mode = "normal"
target_path = "."
generate_safety_asserts = true
deprecate_by_min_version = true
single_version_file = true

external_libraries = [
    "GLib",
    "GObject",
    "Gtk",
    "Cairo",
    "Gdk",
    "GdkPixbuf"
]

generate = [
    "OsmGpsMap.Map",
    "OsmGpsMap.MapKey_t",
    "OsmGpsMap.MapOsd",
#    "OsmGpsMap.MapPoint",
    "OsmGpsMap.MapPolygon",
    "OsmGpsMap.MapSource_t",
    "OsmGpsMap.MapTrack",
]

builders = [
    "OsmGpsMap.MapBuilder",
    "OsmGpsMap.MapTrackBuilder",
    "OsmGpsMap.MapImageBuilder",
    "OsmGpsMap.MapPolygonBuilder",
    "OsmGpsMap.MapOsdBuilder"
]

manual = [
#    "Atk.ImplementorIface",
    "cairo.Context",
    "GdkPixbuf.Pixbuf",
    "Gdk.EventButton",
    "Gdk.Rectangle",
    "Gdk.RGBA",
    "Gtk.Widget",
    "Gtk.Buildable",
    "Gtk.DrawingArea",
#    "GObject.InitiallyUnowned"
]

[[object]]
name = "OsmGpsMap.MapPoint"
status = "generate"
init_function_expression = "|_ptr| ()"
clear_function_expression = "|_ptr| ()"

[[object]]
name = "OsmGpsMap.MapImage"
status = "generate"
    [[object.function]]
    name = "draw"
        [[object.function.parameter]]
        name = "cr"
        const = true

[[object]]
name = "OsmGpsMap.MapLayer"
status = "generate"
    [[object.function]]
    name = "draw"
        [[object.function.parameter]]
        name = "cr"
        const = true
    [[object.function]]
    name = "button_press"
        [[object.function.parameter]]
        name = "event"
        const = true
