[options]
girs_dir = "gir-files"
library = "OsmGpsMap"
version = "1.0"
min_cfg_version = "1.0"
work_mode = "normal"
target_path = "."
generate_safety_asserts = true

external_libraries = [
    "GLib",
    "GObject",
    "Gtk",
    "Cairo",
    "Gdk",
    "GdkPixbuf"
]

generate = [
    "OsmGpsMap.Map",
    "OsmGpsMap.MapKey_t",
    "OsmGpsMap.MapOsd",
    "OsmGpsMap.MapPoint",
    "OsmGpsMap.MapPolygon",
    "OsmGpsMap.MapSource_t",
    "OsmGpsMap.MapTrack",
]

manual = [
    "cairo.Context",
    "GdkPixbuf.Pixbuf",
    "Gdk.EventButton",
    "Gdk.Rectangle",
    "Gdk.RGBA",
    "Gtk.Widget",
]

[[object]]
name = "OsmGpsMap.MapImage"
status = "generate"
    [[object.function]]
    name = "draw"
        [[object.function.parameter]]
        name = "cr"
        const = true

[[object]]
name = "OsmGpsMap.MapLayer"
status = "generate"
    [[object.function]]
    name = "draw"
        [[object.function.parameter]]
        name = "cr"
        const = true
    [[object.function]]
    name = "button_press"
        [[object.function.parameter]]
        name = "event"
        const = true