[build-dependencies]
pkg-config = "0.3.14"

[dependencies]
cairo-sys-rs = "0.8.0"
gdk-pixbuf-sys = "0.8.0"
gdk-sys = "0.8.0"
glib-sys = "0.8.0"
gobject-sys = "0.8.0"
gtk-sys = "0.8.0"
libc = "0.2.58"

[dev-dependencies]
shell-words = "0.1.0"
tempdir = "0.3.7"

[features]
dox = []

[lib]
name = "osmgpsmap_sys"

[package]
authors = ["Eric Trombly <etrombly@gmail.com>"]
build = "build.rs"
description = "FFI bindings to OsmGpsMap-1.0"
license = "MIT"
links = "osm_gps_map"
name = "osmgpsmap-sys"
readme = "README.md"
repository = "https://github.com/etrombly/osmgpsmap-rs"
version = "0.2.4"
